---
README.md:
    name: "check-service-provider"
    minor_version: "0.1"
    badges:
        - "[![Dependency Status](https://www.versioneye.com/user/projects/53dde6f08e78abc191000044/badge.svg)](https://www.versioneye.com/user/projects/53dde6f08e78abc191000044)"
        - "[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/etna-alternance/composer-check-service-provider/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/etna-alternance/composer-check-service-provider/?branch=master)"
